'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace PRHService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ObjPersonal", [Namespace]:="http://schemas.datacontract.org/2004/07/PRHServiceLibrary.Data.Personal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ObjPersonal
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AforeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CONTRATO_DESCField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CTRO_CTO_DESCField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CajaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CajaBField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CajaFField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CalleField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CartillaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CasaOediField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CentroTField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaseRgoField As Short
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClinicaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ColoniaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContratoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CtaBchField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CtaBnmField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CtaPromexField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CtroCtoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CtroOrgField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CuentabanorteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CuotaGField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CuotaNField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CuotaNpos90Field As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CurpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DelMunField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Dir1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Dir2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DoctoEscolarField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EDO_CIVIL_DESField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ESCOLARIDAD_DESCField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EdoCivilField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailiField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EntidadField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EscolaridadField As Short
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaAntField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaCajaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaEgrField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaIngField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaNacField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaPtoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaTField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechainidField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GdoField As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GpoSField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HorarioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HsmField As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IMssField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private JornadaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private JornadapField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LNacField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LOC_DESCField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MaternoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NBancoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NContratoField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NCuentaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NMadreField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NPadreField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NcredinfoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombresField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumIField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroOldField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ObraField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Obra1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Obra2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Obra3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ParentempField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ParenttipField As Short
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ParentwhoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PaternoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PensionadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PorpaginfoField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PosGField As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PosNField As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PtoPlanField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PuestoField As Short
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PustoDescripField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RFcField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SDiField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SEXI_DESCField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SUCURSAL_DESCField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SdiFijoField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SdiInfoField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SdiVarField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SexoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SuaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SucursalField As Short
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TabField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TallaCbField As Short
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TallaPfField As Short
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TarjetaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TelefonoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoTrabField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UBICACION_DESCField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UbicacionField As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserpasswordField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Afore() As String
            Get
                Return Me.AforeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AforeField, value) <> true) Then
                    Me.AforeField = value
                    Me.RaisePropertyChanged("Afore")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CONTRATO_DESC() As String
            Get
                Return Me.CONTRATO_DESCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CONTRATO_DESCField, value) <> true) Then
                    Me.CONTRATO_DESCField = value
                    Me.RaisePropertyChanged("CONTRATO_DESC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CTRO_CTO_DESC() As String
            Get
                Return Me.CTRO_CTO_DESCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CTRO_CTO_DESCField, value) <> true) Then
                    Me.CTRO_CTO_DESCField = value
                    Me.RaisePropertyChanged("CTRO_CTO_DESC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Caja() As String
            Get
                Return Me.CajaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CajaField, value) <> true) Then
                    Me.CajaField = value
                    Me.RaisePropertyChanged("Caja")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CajaB() As String
            Get
                Return Me.CajaBField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CajaBField, value) <> true) Then
                    Me.CajaBField = value
                    Me.RaisePropertyChanged("CajaB")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CajaF() As String
            Get
                Return Me.CajaFField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CajaFField, value) <> true) Then
                    Me.CajaFField = value
                    Me.RaisePropertyChanged("CajaF")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Calle() As String
            Get
                Return Me.CalleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CalleField, value) <> true) Then
                    Me.CalleField = value
                    Me.RaisePropertyChanged("Calle")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cartilla() As String
            Get
                Return Me.CartillaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CartillaField, value) <> true) Then
                    Me.CartillaField = value
                    Me.RaisePropertyChanged("Cartilla")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CasaOedi() As String
            Get
                Return Me.CasaOediField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CasaOediField, value) <> true) Then
                    Me.CasaOediField = value
                    Me.RaisePropertyChanged("CasaOedi")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CentroT() As Integer
            Get
                Return Me.CentroTField
            End Get
            Set
                If (Me.CentroTField.Equals(value) <> true) Then
                    Me.CentroTField = value
                    Me.RaisePropertyChanged("CentroT")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaseRgo() As Short
            Get
                Return Me.ClaseRgoField
            End Get
            Set
                If (Me.ClaseRgoField.Equals(value) <> true) Then
                    Me.ClaseRgoField = value
                    Me.RaisePropertyChanged("ClaseRgo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Clinica() As String
            Get
                Return Me.ClinicaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClinicaField, value) <> true) Then
                    Me.ClinicaField = value
                    Me.RaisePropertyChanged("Clinica")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Colonia() As String
            Get
                Return Me.ColoniaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ColoniaField, value) <> true) Then
                    Me.ColoniaField = value
                    Me.RaisePropertyChanged("Colonia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Contrato() As String
            Get
                Return Me.ContratoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContratoField, value) <> true) Then
                    Me.ContratoField = value
                    Me.RaisePropertyChanged("Contrato")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cp() As String
            Get
                Return Me.CpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CpField, value) <> true) Then
                    Me.CpField = value
                    Me.RaisePropertyChanged("Cp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CtaBch() As String
            Get
                Return Me.CtaBchField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CtaBchField, value) <> true) Then
                    Me.CtaBchField = value
                    Me.RaisePropertyChanged("CtaBch")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CtaBnm() As String
            Get
                Return Me.CtaBnmField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CtaBnmField, value) <> true) Then
                    Me.CtaBnmField = value
                    Me.RaisePropertyChanged("CtaBnm")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CtaPromex() As String
            Get
                Return Me.CtaPromexField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CtaPromexField, value) <> true) Then
                    Me.CtaPromexField = value
                    Me.RaisePropertyChanged("CtaPromex")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CtroCto() As String
            Get
                Return Me.CtroCtoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CtroCtoField, value) <> true) Then
                    Me.CtroCtoField = value
                    Me.RaisePropertyChanged("CtroCto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CtroOrg() As String
            Get
                Return Me.CtroOrgField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CtroOrgField, value) <> true) Then
                    Me.CtroOrgField = value
                    Me.RaisePropertyChanged("CtroOrg")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cuentabanorte() As String
            Get
                Return Me.CuentabanorteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CuentabanorteField, value) <> true) Then
                    Me.CuentabanorteField = value
                    Me.RaisePropertyChanged("Cuentabanorte")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CuotaG() As Decimal
            Get
                Return Me.CuotaGField
            End Get
            Set
                If (Me.CuotaGField.Equals(value) <> true) Then
                    Me.CuotaGField = value
                    Me.RaisePropertyChanged("CuotaG")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CuotaN() As Decimal
            Get
                Return Me.CuotaNField
            End Get
            Set
                If (Me.CuotaNField.Equals(value) <> true) Then
                    Me.CuotaNField = value
                    Me.RaisePropertyChanged("CuotaN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CuotaNpos90() As Decimal
            Get
                Return Me.CuotaNpos90Field
            End Get
            Set
                If (Me.CuotaNpos90Field.Equals(value) <> true) Then
                    Me.CuotaNpos90Field = value
                    Me.RaisePropertyChanged("CuotaNpos90")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Curp() As String
            Get
                Return Me.CurpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CurpField, value) <> true) Then
                    Me.CurpField = value
                    Me.RaisePropertyChanged("Curp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DelMun() As String
            Get
                Return Me.DelMunField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DelMunField, value) <> true) Then
                    Me.DelMunField = value
                    Me.RaisePropertyChanged("DelMun")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Dir1() As String
            Get
                Return Me.Dir1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Dir1Field, value) <> true) Then
                    Me.Dir1Field = value
                    Me.RaisePropertyChanged("Dir1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Dir2() As String
            Get
                Return Me.Dir2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Dir2Field, value) <> true) Then
                    Me.Dir2Field = value
                    Me.RaisePropertyChanged("Dir2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DoctoEscolar() As String
            Get
                Return Me.DoctoEscolarField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DoctoEscolarField, value) <> true) Then
                    Me.DoctoEscolarField = value
                    Me.RaisePropertyChanged("DoctoEscolar")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EDO_CIVIL_DES() As String
            Get
                Return Me.EDO_CIVIL_DESField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EDO_CIVIL_DESField, value) <> true) Then
                    Me.EDO_CIVIL_DESField = value
                    Me.RaisePropertyChanged("EDO_CIVIL_DES")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ESCOLARIDAD_DESC() As String
            Get
                Return Me.ESCOLARIDAD_DESCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ESCOLARIDAD_DESCField, value) <> true) Then
                    Me.ESCOLARIDAD_DESCField = value
                    Me.RaisePropertyChanged("ESCOLARIDAD_DESC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EdoCivil() As Double
            Get
                Return Me.EdoCivilField
            End Get
            Set
                If (Me.EdoCivilField.Equals(value) <> true) Then
                    Me.EdoCivilField = value
                    Me.RaisePropertyChanged("EdoCivil")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Emaili() As String
            Get
                Return Me.EmailiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailiField, value) <> true) Then
                    Me.EmailiField = value
                    Me.RaisePropertyChanged("Emaili")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Entidad() As String
            Get
                Return Me.EntidadField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EntidadField, value) <> true) Then
                    Me.EntidadField = value
                    Me.RaisePropertyChanged("Entidad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Escolaridad() As Short
            Get
                Return Me.EscolaridadField
            End Get
            Set
                If (Me.EscolaridadField.Equals(value) <> true) Then
                    Me.EscolaridadField = value
                    Me.RaisePropertyChanged("Escolaridad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaAnt() As String
            Get
                Return Me.FechaAntField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaAntField, value) <> true) Then
                    Me.FechaAntField = value
                    Me.RaisePropertyChanged("FechaAnt")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaCaja() As String
            Get
                Return Me.FechaCajaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaCajaField, value) <> true) Then
                    Me.FechaCajaField = value
                    Me.RaisePropertyChanged("FechaCaja")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaEgr() As String
            Get
                Return Me.FechaEgrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaEgrField, value) <> true) Then
                    Me.FechaEgrField = value
                    Me.RaisePropertyChanged("FechaEgr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaIng() As String
            Get
                Return Me.FechaIngField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaIngField, value) <> true) Then
                    Me.FechaIngField = value
                    Me.RaisePropertyChanged("FechaIng")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaNac() As String
            Get
                Return Me.FechaNacField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaNacField, value) <> true) Then
                    Me.FechaNacField = value
                    Me.RaisePropertyChanged("FechaNac")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaPto() As String
            Get
                Return Me.FechaPtoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaPtoField, value) <> true) Then
                    Me.FechaPtoField = value
                    Me.RaisePropertyChanged("FechaPto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaT() As String
            Get
                Return Me.FechaTField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaTField, value) <> true) Then
                    Me.FechaTField = value
                    Me.RaisePropertyChanged("FechaT")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fechainid() As String
            Get
                Return Me.FechainidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechainidField, value) <> true) Then
                    Me.FechainidField = value
                    Me.RaisePropertyChanged("Fechainid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Gdo() As Byte
            Get
                Return Me.GdoField
            End Get
            Set
                If (Me.GdoField.Equals(value) <> true) Then
                    Me.GdoField = value
                    Me.RaisePropertyChanged("Gdo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GpoS() As String
            Get
                Return Me.GpoSField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GpoSField, value) <> true) Then
                    Me.GpoSField = value
                    Me.RaisePropertyChanged("GpoS")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Horario() As String
            Get
                Return Me.HorarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HorarioField, value) <> true) Then
                    Me.HorarioField = value
                    Me.RaisePropertyChanged("Horario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Hsm() As Byte
            Get
                Return Me.HsmField
            End Get
            Set
                If (Me.HsmField.Equals(value) <> true) Then
                    Me.HsmField = value
                    Me.RaisePropertyChanged("Hsm")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IMss() As String
            Get
                Return Me.IMssField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IMssField, value) <> true) Then
                    Me.IMssField = value
                    Me.RaisePropertyChanged("IMss")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Jornada() As String
            Get
                Return Me.JornadaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.JornadaField, value) <> true) Then
                    Me.JornadaField = value
                    Me.RaisePropertyChanged("Jornada")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Jornadap() As Decimal
            Get
                Return Me.JornadapField
            End Get
            Set
                If (Me.JornadapField.Equals(value) <> true) Then
                    Me.JornadapField = value
                    Me.RaisePropertyChanged("Jornadap")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LNac() As Double
            Get
                Return Me.LNacField
            End Get
            Set
                If (Me.LNacField.Equals(value) <> true) Then
                    Me.LNacField = value
                    Me.RaisePropertyChanged("LNac")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LOC_DESC() As String
            Get
                Return Me.LOC_DESCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LOC_DESCField, value) <> true) Then
                    Me.LOC_DESCField = value
                    Me.RaisePropertyChanged("LOC_DESC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Loc() As String
            Get
                Return Me.LocField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocField, value) <> true) Then
                    Me.LocField = value
                    Me.RaisePropertyChanged("Loc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Materno() As String
            Get
                Return Me.MaternoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MaternoField, value) <> true) Then
                    Me.MaternoField = value
                    Me.RaisePropertyChanged("Materno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NBanco() As String
            Get
                Return Me.NBancoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NBancoField, value) <> true) Then
                    Me.NBancoField = value
                    Me.RaisePropertyChanged("NBanco")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NContrato() As Double
            Get
                Return Me.NContratoField
            End Get
            Set
                If (Me.NContratoField.Equals(value) <> true) Then
                    Me.NContratoField = value
                    Me.RaisePropertyChanged("NContrato")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NCuenta() As String
            Get
                Return Me.NCuentaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NCuentaField, value) <> true) Then
                    Me.NCuentaField = value
                    Me.RaisePropertyChanged("NCuenta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NMadre() As String
            Get
                Return Me.NMadreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NMadreField, value) <> true) Then
                    Me.NMadreField = value
                    Me.RaisePropertyChanged("NMadre")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NPadre() As String
            Get
                Return Me.NPadreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NPadreField, value) <> true) Then
                    Me.NPadreField = value
                    Me.RaisePropertyChanged("NPadre")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Ncredinfo() As String
            Get
                Return Me.NcredinfoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NcredinfoField, value) <> true) Then
                    Me.NcredinfoField = value
                    Me.RaisePropertyChanged("Ncredinfo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nombre() As String
            Get
                Return Me.NombreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreField, value) <> true) Then
                    Me.NombreField = value
                    Me.RaisePropertyChanged("Nombre")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nombres() As String
            Get
                Return Me.NombresField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombresField, value) <> true) Then
                    Me.NombresField = value
                    Me.RaisePropertyChanged("Nombres")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumE() As String
            Get
                Return Me.NumEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumEField, value) <> true) Then
                    Me.NumEField = value
                    Me.RaisePropertyChanged("NumE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumI() As String
            Get
                Return Me.NumIField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumIField, value) <> true) Then
                    Me.NumIField = value
                    Me.RaisePropertyChanged("NumI")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Numero() As Integer
            Get
                Return Me.NumeroField
            End Get
            Set
                If (Me.NumeroField.Equals(value) <> true) Then
                    Me.NumeroField = value
                    Me.RaisePropertyChanged("Numero")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroOld() As Integer
            Get
                Return Me.NumeroOldField
            End Get
            Set
                If (Me.NumeroOldField.Equals(value) <> true) Then
                    Me.NumeroOldField = value
                    Me.RaisePropertyChanged("NumeroOld")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Obra() As String
            Get
                Return Me.ObraField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObraField, value) <> true) Then
                    Me.ObraField = value
                    Me.RaisePropertyChanged("Obra")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Obra1() As String
            Get
                Return Me.Obra1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Obra1Field, value) <> true) Then
                    Me.Obra1Field = value
                    Me.RaisePropertyChanged("Obra1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Obra2() As String
            Get
                Return Me.Obra2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Obra2Field, value) <> true) Then
                    Me.Obra2Field = value
                    Me.RaisePropertyChanged("Obra2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Obra3() As String
            Get
                Return Me.Obra3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Obra3Field, value) <> true) Then
                    Me.Obra3Field = value
                    Me.RaisePropertyChanged("Obra3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Parentemp() As String
            Get
                Return Me.ParentempField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ParentempField, value) <> true) Then
                    Me.ParentempField = value
                    Me.RaisePropertyChanged("Parentemp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Parenttip() As Short
            Get
                Return Me.ParenttipField
            End Get
            Set
                If (Me.ParenttipField.Equals(value) <> true) Then
                    Me.ParenttipField = value
                    Me.RaisePropertyChanged("Parenttip")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Parentwho() As String
            Get
                Return Me.ParentwhoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ParentwhoField, value) <> true) Then
                    Me.ParentwhoField = value
                    Me.RaisePropertyChanged("Parentwho")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Paterno() As String
            Get
                Return Me.PaternoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PaternoField, value) <> true) Then
                    Me.PaternoField = value
                    Me.RaisePropertyChanged("Paterno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Pensionado() As String
            Get
                Return Me.PensionadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PensionadoField, value) <> true) Then
                    Me.PensionadoField = value
                    Me.RaisePropertyChanged("Pensionado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Porpaginfo() As Decimal
            Get
                Return Me.PorpaginfoField
            End Get
            Set
                If (Me.PorpaginfoField.Equals(value) <> true) Then
                    Me.PorpaginfoField = value
                    Me.RaisePropertyChanged("Porpaginfo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PosG() As Byte
            Get
                Return Me.PosGField
            End Get
            Set
                If (Me.PosGField.Equals(value) <> true) Then
                    Me.PosGField = value
                    Me.RaisePropertyChanged("PosG")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PosN() As Byte
            Get
                Return Me.PosNField
            End Get
            Set
                If (Me.PosNField.Equals(value) <> true) Then
                    Me.PosNField = value
                    Me.RaisePropertyChanged("PosN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PtoPlan() As String
            Get
                Return Me.PtoPlanField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PtoPlanField, value) <> true) Then
                    Me.PtoPlanField = value
                    Me.RaisePropertyChanged("PtoPlan")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Puesto() As Short
            Get
                Return Me.PuestoField
            End Get
            Set
                If (Me.PuestoField.Equals(value) <> true) Then
                    Me.PuestoField = value
                    Me.RaisePropertyChanged("Puesto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PustoDescrip() As String
            Get
                Return Me.PustoDescripField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PustoDescripField, value) <> true) Then
                    Me.PustoDescripField = value
                    Me.RaisePropertyChanged("PustoDescrip")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RFc() As String
            Get
                Return Me.RFcField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RFcField, value) <> true) Then
                    Me.RFcField = value
                    Me.RaisePropertyChanged("RFc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SDi() As Decimal
            Get
                Return Me.SDiField
            End Get
            Set
                If (Me.SDiField.Equals(value) <> true) Then
                    Me.SDiField = value
                    Me.RaisePropertyChanged("SDi")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SEXI_DESC() As String
            Get
                Return Me.SEXI_DESCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SEXI_DESCField, value) <> true) Then
                    Me.SEXI_DESCField = value
                    Me.RaisePropertyChanged("SEXI_DESC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SUCURSAL_DESC() As String
            Get
                Return Me.SUCURSAL_DESCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SUCURSAL_DESCField, value) <> true) Then
                    Me.SUCURSAL_DESCField = value
                    Me.RaisePropertyChanged("SUCURSAL_DESC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SdiFijo() As Decimal
            Get
                Return Me.SdiFijoField
            End Get
            Set
                If (Me.SdiFijoField.Equals(value) <> true) Then
                    Me.SdiFijoField = value
                    Me.RaisePropertyChanged("SdiFijo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SdiInfo() As Decimal
            Get
                Return Me.SdiInfoField
            End Get
            Set
                If (Me.SdiInfoField.Equals(value) <> true) Then
                    Me.SdiInfoField = value
                    Me.RaisePropertyChanged("SdiInfo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SdiVar() As Decimal
            Get
                Return Me.SdiVarField
            End Get
            Set
                If (Me.SdiVarField.Equals(value) <> true) Then
                    Me.SdiVarField = value
                    Me.RaisePropertyChanged("SdiVar")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Sexo() As String
            Get
                Return Me.SexoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SexoField, value) <> true) Then
                    Me.SexoField = value
                    Me.RaisePropertyChanged("Sexo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As String
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Sua() As String
            Get
                Return Me.SuaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SuaField, value) <> true) Then
                    Me.SuaField = value
                    Me.RaisePropertyChanged("Sua")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Sucursal() As Short
            Get
                Return Me.SucursalField
            End Get
            Set
                If (Me.SucursalField.Equals(value) <> true) Then
                    Me.SucursalField = value
                    Me.RaisePropertyChanged("Sucursal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Tab() As String
            Get
                Return Me.TabField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TabField, value) <> true) Then
                    Me.TabField = value
                    Me.RaisePropertyChanged("Tab")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TallaCb() As Short
            Get
                Return Me.TallaCbField
            End Get
            Set
                If (Me.TallaCbField.Equals(value) <> true) Then
                    Me.TallaCbField = value
                    Me.RaisePropertyChanged("TallaCb")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TallaPf() As Short
            Get
                Return Me.TallaPfField
            End Get
            Set
                If (Me.TallaPfField.Equals(value) <> true) Then
                    Me.TallaPfField = value
                    Me.RaisePropertyChanged("TallaPf")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Tarjeta() As String
            Get
                Return Me.TarjetaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TarjetaField, value) <> true) Then
                    Me.TarjetaField = value
                    Me.RaisePropertyChanged("Tarjeta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Telefono() As String
            Get
                Return Me.TelefonoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelefonoField, value) <> true) Then
                    Me.TelefonoField = value
                    Me.RaisePropertyChanged("Telefono")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Tipo() As String
            Get
                Return Me.TipoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoField, value) <> true) Then
                    Me.TipoField = value
                    Me.RaisePropertyChanged("Tipo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoTrab() As String
            Get
                Return Me.TipoTrabField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoTrabField, value) <> true) Then
                    Me.TipoTrabField = value
                    Me.RaisePropertyChanged("TipoTrab")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UBICACION_DESC() As String
            Get
                Return Me.UBICACION_DESCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UBICACION_DESCField, value) <> true) Then
                    Me.UBICACION_DESCField = value
                    Me.RaisePropertyChanged("UBICACION_DESC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Ubicacion() As Byte
            Get
                Return Me.UbicacionField
            End Get
            Set
                If (Me.UbicacionField.Equals(value) <> true) Then
                    Me.UbicacionField = value
                    Me.RaisePropertyChanged("Ubicacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Userpassword() As String
            Get
                Return Me.UserpasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserpasswordField, value) <> true) Then
                    Me.UserpasswordField = value
                    Me.RaisePropertyChanged("Userpassword")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ObjAvisosAusencia", [Namespace]:="http://schemas.datacontract.org/2004/07/PRHServiceLibrary.Data.AvisosAusencia"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ObjAvisosAusencia
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AutorizaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CicloField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CondicsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CtroCtoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DiasField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExpiraField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaFField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaIField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FolioField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IntervaloField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MotivoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Observ1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Observ2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PuestoField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Autoriza() As String
            Get
                Return Me.AutorizaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AutorizaField, value) <> true) Then
                    Me.AutorizaField = value
                    Me.RaisePropertyChanged("Autoriza")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Ciclo() As String
            Get
                Return Me.CicloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CicloField, value) <> true) Then
                    Me.CicloField = value
                    Me.RaisePropertyChanged("Ciclo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Condics() As String
            Get
                Return Me.CondicsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CondicsField, value) <> true) Then
                    Me.CondicsField = value
                    Me.RaisePropertyChanged("Condics")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CtroCto() As String
            Get
                Return Me.CtroCtoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CtroCtoField, value) <> true) Then
                    Me.CtroCtoField = value
                    Me.RaisePropertyChanged("CtroCto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Dias() As Long
            Get
                Return Me.DiasField
            End Get
            Set
                If (Me.DiasField.Equals(value) <> true) Then
                    Me.DiasField = value
                    Me.RaisePropertyChanged("Dias")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Expira() As String
            Get
                Return Me.ExpiraField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExpiraField, value) <> true) Then
                    Me.ExpiraField = value
                    Me.RaisePropertyChanged("Expira")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fecha() As String
            Get
                Return Me.FechaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaField, value) <> true) Then
                    Me.FechaField = value
                    Me.RaisePropertyChanged("Fecha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaF() As String
            Get
                Return Me.FechaFField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaFField, value) <> true) Then
                    Me.FechaFField = value
                    Me.RaisePropertyChanged("FechaF")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaI() As String
            Get
                Return Me.FechaIField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaIField, value) <> true) Then
                    Me.FechaIField = value
                    Me.RaisePropertyChanged("FechaI")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Folio() As Long
            Get
                Return Me.FolioField
            End Get
            Set
                If (Me.FolioField.Equals(value) <> true) Then
                    Me.FolioField = value
                    Me.RaisePropertyChanged("Folio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Intervalo() As String
            Get
                Return Me.IntervaloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IntervaloField, value) <> true) Then
                    Me.IntervaloField = value
                    Me.RaisePropertyChanged("Intervalo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Loc() As String
            Get
                Return Me.LocField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocField, value) <> true) Then
                    Me.LocField = value
                    Me.RaisePropertyChanged("Loc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Motivo() As String
            Get
                Return Me.MotivoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MotivoField, value) <> true) Then
                    Me.MotivoField = value
                    Me.RaisePropertyChanged("Motivo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nombre() As String
            Get
                Return Me.NombreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreField, value) <> true) Then
                    Me.NombreField = value
                    Me.RaisePropertyChanged("Nombre")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Numero() As Integer
            Get
                Return Me.NumeroField
            End Get
            Set
                If (Me.NumeroField.Equals(value) <> true) Then
                    Me.NumeroField = value
                    Me.RaisePropertyChanged("Numero")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Observ1() As String
            Get
                Return Me.Observ1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Observ1Field, value) <> true) Then
                    Me.Observ1Field = value
                    Me.RaisePropertyChanged("Observ1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Observ2() As String
            Get
                Return Me.Observ2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Observ2Field, value) <> true) Then
                    Me.Observ2Field = value
                    Me.RaisePropertyChanged("Observ2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Puesto() As Double
            Get
                Return Me.PuestoField
            End Get
            Set
                If (Me.PuestoField.Equals(value) <> true) Then
                    Me.PuestoField = value
                    Me.RaisePropertyChanged("Puesto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As String
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ObjMotivoAviso", [Namespace]:="http://schemas.datacontract.org/2004/07/PRHServiceLibrary.Data.MotivoAviso"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ObjMotivoAviso
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VacField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cod() As String
            Get
                Return Me.CodField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodField, value) <> true) Then
                    Me.CodField = value
                    Me.RaisePropertyChanged("Cod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Descrip() As String
            Get
                Return Me.DescripField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripField, value) <> true) Then
                    Me.DescripField = value
                    Me.RaisePropertyChanged("Descrip")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Vac() As String
            Get
                Return Me.VacField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VacField, value) <> true) Then
                    Me.VacField = value
                    Me.RaisePropertyChanged("Vac")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ObjLogin", [Namespace]:="http://schemas.datacontract.org/2004/07/PRHServiceLibrary.Data.Login"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ObjLogin
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContraseniaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsuarioField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Contrasenia() As String
            Get
                Return Me.ContraseniaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContraseniaField, value) <> true) Then
                    Me.ContraseniaField = value
                    Me.RaisePropertyChanged("Contrasenia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Usuario() As Integer
            Get
                Return Me.UsuarioField
            End Get
            Set
                If (Me.UsuarioField.Equals(value) <> true) Then
                    Me.UsuarioField = value
                    Me.RaisePropertyChanged("Usuario")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="PRHService.IPersonal")>  _
    Public Interface IPersonal
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonal/GetPersonal", ReplyAction:="http://tempuri.org/IPersonal/GetPersonalResponse")>  _
        Function GetPersonal(ByVal NUMERO As String) As PRHService.ObjPersonal
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IPersonalChannel
        Inherits PRHService.IPersonal, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PersonalClient
        Inherits System.ServiceModel.ClientBase(Of PRHService.IPersonal)
        Implements PRHService.IPersonal
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetPersonal(ByVal NUMERO As String) As PRHService.ObjPersonal Implements PRHService.IPersonal.GetPersonal
            Return MyBase.Channel.GetPersonal(NUMERO)
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="PRHService.IAvisosAusencia")>  _
    Public Interface IAvisosAusencia
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAvisosAusencia/GetAvisos", ReplyAction:="http://tempuri.org/IAvisosAusencia/GetAvisosResponse")>  _
        Function GetAvisos(ByVal NUMERO As Integer, ByVal MOTIVO As String) As System.Collections.ObjectModel.ObservableCollection(Of PRHService.ObjAvisosAusencia)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAvisosAusencia/UpdateAviso", ReplyAction:="http://tempuri.org/IAvisosAusencia/UpdateAvisoResponse")>  _
        Sub UpdateAviso(ByVal aviso As PRHService.ObjAvisosAusencia)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAvisosAusencia/InsertAviso", ReplyAction:="http://tempuri.org/IAvisosAusencia/InsertAvisoResponse")>  _
        Function InsertAviso(ByVal nuevo As PRHService.ObjAvisosAusencia) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAvisosAusencia/DeleteAviso", ReplyAction:="http://tempuri.org/IAvisosAusencia/DeleteAvisoResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.ObjectModel.ObservableCollection(Of PRHService.ObjMotivoAviso))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PRHService.ObjMotivoAviso)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.ObjectModel.ObservableCollection(Of PRHService.ObjAvisosAusencia))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PRHService.ObjAvisosAusencia)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PRHService.ObjPersonal)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PRHService.ObjLogin))>  _
        Function DeleteAviso(ByVal FOLIO As Integer) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAvisosAusencia/GetMotivo", ReplyAction:="http://tempuri.org/IAvisosAusencia/GetMotivoResponse")>  _
        Function GetMotivo() As System.Collections.ObjectModel.ObservableCollection(Of PRHService.ObjMotivoAviso)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAvisosAusencia/GetEdoVac", ReplyAction:="http://tempuri.org/IAvisosAusencia/GetEdoVacResponse")>  _
        Function GetEdoVac(ByVal NumeroEmpleado As Integer) As System.Collections.ObjectModel.ObservableCollection(Of PRHService.ObjAvisosAusencia)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IAvisosAusenciaChannel
        Inherits PRHService.IAvisosAusencia, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AvisosAusenciaClient
        Inherits System.ServiceModel.ClientBase(Of PRHService.IAvisosAusencia)
        Implements PRHService.IAvisosAusencia
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetAvisos(ByVal NUMERO As Integer, ByVal MOTIVO As String) As System.Collections.ObjectModel.ObservableCollection(Of PRHService.ObjAvisosAusencia) Implements PRHService.IAvisosAusencia.GetAvisos
            Return MyBase.Channel.GetAvisos(NUMERO, MOTIVO)
        End Function
        
        Public Sub UpdateAviso(ByVal aviso As PRHService.ObjAvisosAusencia) Implements PRHService.IAvisosAusencia.UpdateAviso
            MyBase.Channel.UpdateAviso(aviso)
        End Sub
        
        Public Function InsertAviso(ByVal nuevo As PRHService.ObjAvisosAusencia) As String Implements PRHService.IAvisosAusencia.InsertAviso
            Return MyBase.Channel.InsertAviso(nuevo)
        End Function
        
        Public Function DeleteAviso(ByVal FOLIO As Integer) As Object Implements PRHService.IAvisosAusencia.DeleteAviso
            Return MyBase.Channel.DeleteAviso(FOLIO)
        End Function
        
        Public Function GetMotivo() As System.Collections.ObjectModel.ObservableCollection(Of PRHService.ObjMotivoAviso) Implements PRHService.IAvisosAusencia.GetMotivo
            Return MyBase.Channel.GetMotivo
        End Function
        
        Public Function GetEdoVac(ByVal NumeroEmpleado As Integer) As System.Collections.ObjectModel.ObservableCollection(Of PRHService.ObjAvisosAusencia) Implements PRHService.IAvisosAusencia.GetEdoVac
            Return MyBase.Channel.GetEdoVac(NumeroEmpleado)
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="PRHService.ILogin")>  _
    Public Interface ILogin
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILogin/Login", ReplyAction:="http://tempuri.org/ILogin/LoginResponse")>  _
        Function Login(ByVal usuario As String, ByVal contrasenia As String) As PRHService.ObjLogin
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ILoginChannel
        Inherits PRHService.ILogin, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class LoginClient
        Inherits System.ServiceModel.ClientBase(Of PRHService.ILogin)
        Implements PRHService.ILogin
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Login(ByVal usuario As String, ByVal contrasenia As String) As PRHService.ObjLogin Implements PRHService.ILogin.Login
            Return MyBase.Channel.Login(usuario, contrasenia)
        End Function
    End Class
End Namespace
